Serde instance
apache/datasketches-cpp pull request #269
Opened 2022-03-29 19:16 UTC by AlexanderSaydakov

deprecated class-level serde (to be removed later), support serde instance

2022-04-15 19:09 UTC, jmalkin requested changes
I also looked for any remaning instances of `S()` in the headers and the only instances aside from the new methods to handle the old calls was tuple sketch summary destructors.

I think the header size is not needed when serializing the gadget though? Let me know if that's incorrect and I can approve.

2022-04-19 00:07 UTC, AlexanderSaydakov commented on kll/include/kll_sketch_impl.hpp
> +size_t kll_sketch<T, C, S, A>::get_serialized_size_bytes(const SerDe&) const {
the class-level parameter is only used as a default in the declaration

2022-04-19 00:07 UTC, AlexanderSaydakov commented on sampling/include/var_opt_union_impl.hpp
> +    auto gadget_bytes = gadget_.serialize(header_size_bytes, sd);
fixed. thanks

2022-04-19 18:24 UTC, jmalkin approved these changes

2022-04-19 18:25 UTC, jmalkin commented
👍

2022-05-02 20:08 UTC, merged